server: 
  port: 3344 
  
spring:
  application:
    name:  udm-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yyf0716/microservicecloud-config.git #GitHub上面的git仓库名字